os: linux
dist: xenial
language: scala
jdk:
  - openjdk8
script:
  - sbt clean +test
  - sbt coverage coreJVM/test slf4j/test slf4j18/test
  - sbt coverageReport
  - sbt coverageAggregate
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report --skip
cache:
  directories:
    - $HOME/.cache/coursier/v1
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete